In [1]:
!pip install sdv

Requirement already satisfied: sdv in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (0.7.0)
Requirement already satisfied: deepecho<0.2,>=0.1.4 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (0.1.4)
Requirement already satisfied: graphviz<1,>=0.13.2 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (0.16)
Requirement already satisfied: numpy<2,>=1.18.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (1.19.5)
Requirement already satisfied: sdmetrics<0.2.0,>=0.1.2 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (0.1.2)
Requirement already satisfied: pandas<1.1.5,>=1.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (1.1.4)
Requirement already satisfied: rdt<0.4,>=0.2.10 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (0.3.0)
Requirement already satisfied: ctgan<0.4,>=0.3.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (0.3.1)
Requirement already satisfied: scipy<1.6,>=1.1.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (1.5.4)
Requirement already satisfied: copulas<0.5,>=0.4.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdv) (0.4.0)
Requirement already satisfied: matplotlib<3.2.2,>=2.2.2 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from copulas<0.5,>=0.4.0->sdv) (3.2.1)
Requirement already satisfied: scikit-learn<0.24,>=0.21 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from ctgan<0.4,>=0.3.1->sdv) (0.23.2)
Requirement already satisfied: torchvision<1,>=0.4.2 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from ctgan<0.4,>=0.3.1->sdv) (0.8.2)
Requirement already satisfied: packaging in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from ctgan<0.4,>=0.3.1->sdv) (20.9)
Requirement already satisfied: torch<2,>=1.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from ctgan<0.4,>=0.3.1->sdv) (1.7.1)
Requirement already satisfied: tqdm<5,>=4 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from deepecho<0.2,>=0.1.4->sdv) (4.56.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from matplotlib<3.2.2,>=2.2.2->copulas<0.5,>=0.4.0->sdv) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from matplotlib<3.2.2,>=2.2.2->copulas<0.5,>=0.4.0->sdv) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from matplotlib<3.2.2,>=2.2.2->copulas<0.5,>=0.4.0->sdv) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from matplotlib<3.2.2,>=2.2.2->copulas<0.5,>=0.4.0->sdv) (2.4.7)
Requirement already satisfied: six in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from cycler>=0.10->matplotlib<3.2.2,>=2.2.2->copulas<0.5,>=0.4.0->sdv) (1.15.0)
Requirement already satisfied: pytz>=2017.2 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from pandas<1.1.5,>=1.1->sdv) (2021.1)
Requirement already satisfied: Faker<4.15,>=1.0.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from rdt<0.4,>=0.2.10->sdv) (4.14.2)
Requirement already satisfied: text-unidecode==1.3 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from Faker<4.15,>=1.0.1->rdt<0.4,>=0.2.10->sdv) (1.3)
Requirement already satisfied: joblib>=0.11 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from scikit-learn<0.24,>=0.21->ctgan<0.4,>=0.3.1->sdv) (1.0.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from scikit-learn<0.24,>=0.21->ctgan<0.4,>=0.3.1->sdv) (2.1.0)
Requirement already satisfied: seaborn<0.11,>=0.9 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdmetrics<0.2.0,>=0.1.2->sdv) (0.10.1)
Requirement already satisfied: sktime<0.5,>=0.4 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdmetrics<0.2.0,>=0.1.2->sdv) (0.4.3)
Requirement already satisfied: pomegranate<0.13.5,>=0.13.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdmetrics<0.2.0,>=0.1.2->sdv) (0.13.4)
Requirement already satisfied: tsfresh<1,>=0.15 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sdmetrics<0.2.0,>=0.1.2->sdv) (0.17.0)
Requirement already satisfied: networkx>=2.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from pomegranate<0.13.5,>=0.13.0->sdmetrics<0.2.0,>=0.1.2->sdv) (2.5)
Requirement already satisfied: pyyaml in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from pomegranate<0.13.5,>=0.13.0->sdmetrics<0.2.0,>=0.1.2->sdv) (5.4.1)
Requirement already satisfied: decorator>=4.3.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from networkx>=2.0->pomegranate<0.13.5,>=0.13.0->sdmetrics<0.2.0,>=0.1.2->sdv) (4.4.2)
Requirement already satisfied: wheel in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sktime<0.5,>=0.4->sdmetrics<0.2.0,>=0.1.2->sdv) (0.36.2)
Requirement already satisfied: statsmodels>=0.12.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from sktime<0.5,>=0.4->sdmetrics<0.2.0,>=0.1.2->sdv) (0.12.2)
Requirement already satisfied: patsy>=0.5 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from statsmodels>=0.12.0->sktime<0.5,>=0.4->sdmetrics<0.2.0,>=0.1.2->sdv) (0.5.1)
Requirement already satisfied: typing-extensions in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from torch<2,>=1.0->ctgan<0.4,>=0.3.1->sdv) (3.7.4.3)
Requirement already satisfied: pillow>=4.1.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from torchvision<1,>=0.4.2->ctgan<0.4,>=0.3.1->sdv) (8.1.0)
Requirement already satisfied: dask[dataframe]>=2.9.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (2021.1.1)
Requirement already satisfied: distributed>=2.11.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (2021.1.1)
Requirement already satisfied: requests>=2.9.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (2.25.1)
Requirement already satisfied: toolz>=0.8.2 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from dask[dataframe]>=2.9.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (0.11.1)
Requirement already satisfied: fsspec>=0.6.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from dask[dataframe]>=2.9.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (0.8.5)
Requirement already satisfied: partd>=0.3.10 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from dask[dataframe]>=2.9.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (1.1.0)
Requirement already satisfied: cloudpickle>=1.5.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (1.6.0)
Requirement already satisfied: setuptools in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (51.0.0)
Requirement already satisfied: click>=6.6 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (7.1.2)
Requirement already satisfied: msgpack>=0.6.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (1.0.2)
Requirement already satisfied: tblib>=1.6.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (1.7.0)
Requirement already satisfied: tornado>=5 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (6.1)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (2.3.0)
Requirement already satisfied: psutil>=5.0 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (5.8.0)
Requirement already satisfied: zict>=0.1.3 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (2.0.0)

Requirement already satisfied: locket in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from partd>=0.3.10->dask[dataframe]>=2.9.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (0.2.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from requests>=2.9.1->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from requests>=2.9.1->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (1.26.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from requests>=2.9.1->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from requests>=2.9.1->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (2.10)
Requirement already satisfied: heapdict in /Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages (from zict>=0.1.3->distributed>=2.11.0->tsfresh<1,>=0.15->sdmetrics<0.2.0,>=0.1.2->sdv) (1.0.1)

# SDV Demo

In [2]:
from sdv import load_demo
metadata, tables = load_demo(metadata=True)

In [3]:
metadata

Metadata
  root_path: .
  tables: ['users', 'sessions', 'transactions']
  relationships:
    sessions.user_id -> users.user_id
    transactions.session_id -> sessions.session_id

In [4]:
metadata.visualize()

In [5]:
tables

{'users':    user_id country gender  age
 0        0      US      M   34
 1        1      UK      F   23
 2        2      ES   None   44
 3        3      UK      M   22
 4        4      US      F   54
 5        5      DE      M   57
 6        6      BG      F   45
 7        7      ES   None   41
 8        8      FR      F   23
 9        9      UK   None   30,
 'sessions':    session_id  user_id  device       os
 0           0        0  mobile  android
 1           1        1  tablet      ios
 2           2        1  tablet  android
 3           3        2  mobile  android
 4           4        4  mobile      ios
 5           5        5  mobile  android
 6           6        6  mobile      ios
 7           7        6  tablet      ios
 8           8        6  mobile      ios
 9           9        8  tablet      ios,
 'transactions':    transaction_id  session_id           timestamp  amount  approved
 0               0           0 2019-01-01 12:34:32   100.0      True
 1               1           0 2019-01-01 12:42:21    55.3      True
 2               2           1 2019-01-07 17:23:11    79.5      True
 3               3           3 2019-01-10 11:08:57   112.1     False
 4               4           5 2019-01-10 21:54:08   110.0     False
 5               5           5 2019-01-11 11:21:20    76.3      True
 6               6           7 2019-01-22 14:44:10    89.5      True
 7               7           8 2019-01-23 10:14:09   132.1     False
 8               8           9 2019-01-27 16:09:17    68.0      True
 9               9           9 2019-01-29 12:10:48    99.9      True}

In [6]:
from sdv import SDV

sdv = SDV()
sdv.fit(metadata, tables)

In [7]:
sdv.sample_all()

{'users':    user_id country gender  age
 0        0      DE      M   46
 1        1      DE      M   41
 2        2      UK      M   27
 3        3      US      M   58
 4        4      US      F   31
 5        5      ES    NaN   34
 6        6      UK      F   37
 7        7      UK      M   40
 8        8      ES      F   45
 9        9      FR    NaN   40,
 'sessions':     session_id  user_id  device   os
 0            0        0  tablet  ios
 1            1        0  tablet  ios
 2            2        1  mobile  ios
 3            3        2  tablet  ios
 4            4        5  tablet  ios
 5            5        5  tablet  ios
 6            6        5  tablet  ios
 7            7        6  mobile  ios
 8            8        8  mobile  ios
 9            9        8  mobile  ios
 10          10        9  tablet  ios
 11          11        9  mobile  ios,
 'transactions':    transaction_id  session_id           timestamp      amount  approved
 0               0           2 2019-01-21 22:36:26  107.283193     False
 1               1           2 2019-01-21 22:36:26  107.283005     False}

# Synthesize the data

In [8]:
import pandas as pd

ratings_df = pd.read_csv("../data/restaurant_data_reformatted/ratings.csv")
users_df = pd.read_csv("../data/restaurant_data_reformatted/users.csv")
restaurants_df = pd.read_csv("../data/restaurant_data_reformatted/restaurants.csv")

In [9]:
ratings_df.head()

  userID  placeID  rating  food_rating  service_rating
0  U1077   135085       2            2               2
1  U1077   135038       2            2               1
2  U1077   132825       2            2               2
3  U1077   135060       1            2               2
4  U1068   135104       1            1               2

In [10]:
users_df.head()

,userID,smoker,drink_level,dress_preference,ambience,transport,marital_status,hijos,birth_year,interest,...,Swiss,Tapas,Tea_House,Tex-Mex,Thai,Tibetan,Tunisian,Turkish,Vegetarian,Vietnamese
0,U1001,False,abstemious,informal,family,on foot,single,independent,1989,variety,...,0,0,0,0,0,0,0,0,0,0
1,U1002,False,abstemious,informal,family,public,single,independent,1990,technology,...,0,0,0,0,0,0,0,0,0,0
2,U1003,False,social drinker,formal,family,public,single,independent,1989,none,...,0,0,0,0,0,0,0,0,0,0
3,U1004,False,abstemious,informal,family,public,single,independent,1940,variety,...,0,0,0,0,0,0,0,0,0,0
4,U1005,False,abstemious,no preference,family,public,single,independent,1992,none,...,0,0,0,0,0,0,0,0,0,0

In [34]:
import numpy as np
users_df.iloc[[1]]["userID"]

1    U1002U1002
Name: userID, dtype: object

In [11]:
restaurants_df

,placeID,Afghan,African,American,Armenian,Asian,Bagels,Bakery,Bar,Bar_Pub_Brewery,...,Soup,Southern,Southwestern,Spanish,Steaks,Sushi,Thai,Turkish,Vegetarian,Vietnamese
0,132001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,132002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,132003,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,132004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,132005,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
764,135105,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
765,135106,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
766,135107,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
767,135109,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
768,135110,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [12]:
restaurants_df.describe()

,placeID,Afghan,African,American,Armenian,Asian,Bagels,Bakery,Bar,Bar_Pub_Brewery,...,Soup,Southern,Southwestern,Spanish,Steaks,Sushi,Thai,Turkish,Vegetarian,Vietnamese
count,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,...,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000
mean,132840.681404,0.001300,0.003901,0.076723,0.006502,0.009103,0.001300,0.007802,0.041612,0.031209,...,0.001300,0.001300,0.003901,0.003901,0.010403,0.007802,0.001300,0.001300,0.013004,0.002601
std,827.820287,0.036061,0.062378,0.266325,0.080424,0.095035,0.036061,0.088043,0.199832,0.173996,...,0.036061,0.036061,0.062378,0.062378,0.101530,0.088043,0.036061,0.036061,0.113365,0.050965
min,132001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,132354.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,132648.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,132894.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,135110.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [13]:
_merged = pd.merge(ratings_df, users_df, on="userID")
final_df = pd.merge(_merged, restaurants_df, on="placeID")

In [14]:
final_df

,userID,placeID,rating,food_rating,service_rating,smoker,drink_level,dress_preference,ambience,transport,...,Soup_y,Southern_y,Southwestern_y,Spanish_y,Steaks_y,Sushi_y,Thai_y,Turkish_y,Vegetarian_y,Vietnamese_y
0,U1077,135085,2,2,2,False,social drinker,elegant,family,public,...,0,0,0,0,0,0,0,0,0,0
1,U1108,135085,1,2,1,False,abstemious,informal,solitary,public,...,0,0,0,0,0,0,0,0,0,0
2,U1081,135085,1,2,1,False,casual drinker,informal,family,public,...,0,0,0,0,0,0,0,0,0,0
3,U1001,135085,0,1,1,False,abstemious,informal,family,on foot,...,0,0,0,0,0,0,0,0,0,0
4,U1056,135085,2,2,2,False,social drinker,informal,family,on foot,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
868,U1006,132922,2,1,2,True,social drinker,no preference,friends,car owner,...,0,0,0,0,0,0,0,0,0,0
869,U1003,132937,2,2,1,False,social drinker,formal,family,public,...,0,0,0,0,0,0,0,0,0,0
870,U1027,132937,1,1,1,True,social drinker,no preference,family,public,...,0,0,0,0,0,0,0,0,0,0
871,U1029,132937,1,1,1,True,casual drinker,formal,family,public,...,0,0,0,0,0,0,0,0,0,0
872,U1086,132937,2,0,1,False,social drinker,no preference,family,car owner,...,0,0,0,0,0,0,0,0,0,0

In [15]:
candidate_df = final_df.drop(["placeID", "userID"], axis=1)

In [21]:
candidate_df.to_csv("../data/restaurant_data_reformatted/source.csv")

In [16]:
from sdv import Metadata

metadata = Metadata()
metadata

Metadata
  root_path: .
  tables: []
  relationships:

In [17]:
from sdv.tabular import GaussianCopula

model = GaussianCopula()
model.fit(candidate_df)

/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py:4965: RuntimeWarning: divide by zero encountered in true_divide
  return c**2 / (c**2 - n**2)
/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:2429: RuntimeWarning: invalid value encountered in double_scalars
  Lhat = muhat - Shat*mu
/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py:621: RuntimeWarning: invalid value encountered in sqrt
  sk = 2*(b-a)*np.sqrt(a + b + 1) / (a + b + 2) / np.sqrt(a*b)
/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The number of calls to function has reached maxfev = 600.
  warnings.warn(msg, RuntimeWarning)
/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/copulas/univariate/truncated_gaussian.py:43: RuntimeWarning: divide by zero encountered in double_scalars
  a = (self.min - loc) / scale
/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/copulas/univariate/truncated_gaussian.py:44: RuntimeWarning: divide by zero encountered in double_scalars
  b = (self.max - loc) / scale
/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/copulas/univariate/truncated_gaussian.py:43: RuntimeWarning: invalid value encountered in double_scalars
  a = (self.min - loc) / scale
/Users/vldpro/Workspace/university/recsys/.venv/lib/python3.7/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the
  improvement from the last five Jacobian evaluations.
  warnings.warn(msg, RuntimeWarning)

In [18]:
syn_data = model.sample(100000)

In [19]:
syn_data

,rating,food_rating,service_rating,smoker,drink_level,dress_preference,ambience,transport,marital_status,hijos,...,Soup_y,Southern_y,Southwestern_y,Spanish_y,Steaks_y,Sushi_y,Thai_y,Turkish_y,Vegetarian_y,Vietnamese_y
0,1,1,2,False,social drinker,formal,family,public,single,independent,...,0,0,0,0,0,0,0,0,0,0
1,1,2,1,False,social drinker,elegant,family,public,single,dependent,...,0,0,0,0,0,0,0,0,0,0
2,2,1,1,False,social drinker,elegant,family,public,single,independent,...,0,0,0,0,0,0,0,0,0,0
3,2,1,2,False,social drinker,elegant,family,car owner,single,independent,...,0,0,0,0,0,0,0,0,0,0
4,2,1,1,False,social drinker,elegant,family,public,single,dependent,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2,2,2,False,social drinker,informal,family,public,single,independent,...,0,0,0,0,0,0,0,0,0,0
99996,1,1,1,False,casual drinker,formal,family,public,single,independent,...,0,0,0,0,0,0,0,0,0,0
99997,0,0,0,True,casual drinker,formal,family,public,single,independent,...,0,0,0,0,0,0,0,0,0,0
99998,1,0,1,True,social drinker,informal,friends,public,single,independent,...,0,0,0,0,0,0,0,0,0,0
99999,1,2,1,False,social drinker,no preference,friends,car owner,single,independent,...,0,0,0,0,0,0,0,0,0,0

In [20]:
syn_data.to_csv("../data/restaurant_data_reformatted/synthetic_data.csv")